### PR TITLE
Issue 319 replace placeholder img and text for Home page

### PR DESCRIPTION
**Pull request by almazhankapan**

### CODE REVIEW

**Review by LevBernstein — CHANGES_REQUESTED** [review]
Great work, Alma! A few minor things I'd suggest changing.

- I think we should just refer to the project as TV Tracker, not TV Tracker app, as it feels more branded and rolls off the tongue better.
- I would suggest moving the first video to below the first block of text, so the prospective users have something to look at sooner.
- I don't think we really need to give Trakt any free publicity; I think we can remove the mention of their database. In terms of the last line of the first block of text, I would suggest changing it to something like "Our app is and always will be free; you only need an email address to register."

Looks all good besides that.

**Comment by almazhankapan** [comment]
> Great work, Alma! A few minor things I'd suggest changing.
> thank you :) 
)  > * I think we should just refer to the project as TV Tracker, not TV Tracker app, as it feels more branded and rolls off the tongue better.-sounds good
> * I would suggest moving the first video to below the first block of text, so the prospective users have something to look at sooner.--for this one, probably image follows the text as the text provides a description hehe
> * I don't think we really need to give Trakt any free publicity; I think we can remove the mention of their database. In terms of the last line of the first block of text, I would suggest changing it to something like "Our app is and always will be free; you only need an email address to register."--yup, will do that
> 
> Looks all good besides that.

**Comment by LevBernstein** [comment]
> > * I would suggest moving the first video to below the first block of text, so the prospective users have something to look at sooner.--for this one, probably image follows the text as the text provides a description hehe

Regardless, I would suggest the home page more follow something similar to the prototype, with an image/video clearly visible as soon as the home page loads; that helps to draw in the user in a way that a page of pure text doesn't

**Comment by almazhankapan** [comment]
> > > * I would suggest moving the first video to below the first block of text, so the prospective users have something to look at sooner.--for this one, probably image follows the text as the text provides a description hehe
> 
> Regardless, I would suggest the home page more follow something similar to the prototype, with an image/video clearly visible as soon as the home page loads; that helps to draw in the user in a way that a page of pure text doesn't

mm I can add a new image after first text block then, but I feel that description of the image should go before the image for easier view/understanding

**Review by sam-eng — APPROVED** [review]
Looks good to me Alma! Sorry for not reviewing this earlier

**Comment by almazhankapan** [comment]
> Looks good to me Alma! Sorry for not reviewing this earlier

thanks a lot! no worries 👍

**Pull request merged**
